import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
//import { Inter } from "next/font/google";
import "./globals.css";
import NavLinks from "@/app/ui/nav-links";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>  
        {/* TODO: select default font */}
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <div className="flex h-full flex-col px-3 py-4 md:px-2">
              <div className="flex grow flex-row justify-between space-x-2 md:flex-col md:space-x-0 md:space-y-2">
                <NavLinks />
              </div>
            </div>
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
      </body>
    </html>   
  );
}
